腾讯: big
阿里巴巴: big
字节跳动: big
美团: big
华为: big
京东: big
小米: big
携程: big
快手: big
网易: big
哔哩哔哩: big
滴滴: big
拼多多: big
贝壳: big
唯品会: big
招银网络: big
OPPO: big
vivo: big
蚂蚁集团: big

深信服: medium
用友网络: medium
金山办公: medium
顺丰科技: medium
得物: medium
同程旅行: medium
猿辅导: medium

一些初创公司: small
示例小公司: small